DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS business_entities;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS purchase_invoices;
DROP TABLE IF EXISTS purchase_invoice_items;
DROP TABLE IF EXISTS sales_invoices;
DROP TABLE IF EXISTS sales_invoice_items;
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS receipt_items;
